// Code generated by "stringer -type=Direction -linecomment -output=direction_string.go"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Left-1]
	_ = x[Right-2]
}

const _Direction_name = "leftright"

var _Direction_index = [...]uint8{0, 4, 9}

func (i Direction) String() string {
	i -= 1
	if i >= Direction(len(_Direction_index)-1) {
		return "Direction(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}
