// Code generated by "stringer -type=State -linecomment -output=state_string.go"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateIdle-1]
	_ = x[StateLeft-2]
	_ = x[StateRight-3]
	_ = x[StateJumping-4]
	_ = x[StateFalling-5]
	_ = x[StateAttack-6]
	_ = x[StateCrouch-7]
	_ = x[StateDead-8]
}

const _State_name = "idleleftrightjumpingfallingattackcrouchdead"

var _State_index = [...]uint8{0, 4, 8, 13, 20, 27, 33, 39, 43}

func (i State) String() string {
	i -= 1
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
